project:
  type: website

quartodoc:
  dir: docs/api
  package: axolotl
  title: API Reference
  sections:
    - title: Core
      desc: Core functionality for training
      contents:
        - train
        - evaluate
        - datasets
    - title: CLI
      desc: Command-line interface
      contents:
        - cli.main
        - cli.train
        - cli.evaluate
    - title: Prompt Strategies
      desc: Prompt formatting strategies
      contents:
        - prompt_strategies.base
        - prompt_strategies.chat_template
    - title: Utils
      desc: Utility functions
      contents:
        - utils.models
        - utils.tokenization

website:
  title: "Axolotl"
  description: "We make fine-tuning accessible, scalable, and fun"
  favicon: favicon.jpg

  navbar:
    logo: image/axolotl_logo_digital_white.svg
    title: false
    background: dark
    pinned: false
    collapse: false
    tools:
    - icon: twitter
      href: https://twitter.com/axolotl_ai
    - icon: github
      href: https://github.com/axolotl-ai-cloud/axolotl/
    - icon: discord
      href: https://discord.gg/7m9sfhzaf3

  sidebar:
      pinned: true
      collapse-level: 2
      style: docked
      contents:
        - text: Home
          href: index.qmd

        - section: "Getting Started"
          contents:
            - docs/getting-started.qmd
            - docs/installation.qmd
            - docs/inference.qmd
            - docs/cli.qmd
            - docs/config.qmd

        - section: "Dataset Formats"
          contents: docs/dataset-formats/*

        - section: "Deployments"
          contents:
            - docs/docker.qmd
            - docs/multi-gpu.qmd
            - docs/multi-node.qmd
            - docs/ray-integration.qmd
            - docs/amd_hpc.qmd
            - docs/mac.qmd

        - section: "How To Guides"
          contents:
            - docs/multimodal.qmd
            - docs/rlhf.qmd
            - docs/reward_modelling.qmd
            - docs/lr_groups.qmd
            - docs/lora_optims.qmd

        - section: "Core Concepts"
          contents:
            - docs/batch_vs_grad.qmd
            - docs/dataset_preprocessing.qmd
            - docs/multipack.qmd

        - section: "Advanced Features"
          contents:
            - docs/fsdp_qlora.qmd
            - docs/unsloth.qmd
            - docs/torchao.qmd
            - docs/custom_integrations.qmd

        - section: "Troubleshooting"
          contents:
            - docs/faq.qmd
            - docs/debugging.qmd
            - docs/nccl.qmd

<<<<<<< HEAD
=======
        - section: "Reference"
          contents:
            - docs/config.qmd
            - section: "API Reference"
              contents: docs/api/**/*.qmd

>>>>>>> 5d96b2a95 (quartodoc integration)
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
