project:
  type: website

website:
  title: "Axolotl"
  description: "Fine-tuning"
  favicon: favicon.jpg
  navbar:
    title: Axolotl
    background: dark
    pinned: false
    collapse: false
    tools:
    - icon: twitter
      href: https://twitter.com/axolotl_ai
    - icon: github
      href: https://github.com/axolotl-ai-cloud/axolotl/
    - icon: discord
      href: https://discord.gg/7m9sfhzaf3

  sidebar:
    pinned: true
    collapse-level: 2
    style: docked
    contents:
      - text: Home
        href: index.qmd
      - section: "How-To Guides"
        contents:
          - docs/debugging.qmd
          - docs/multipack.qmd
          - docs/fsdp_qlora.qmd
          - docs/input_output.qmd
          - docs/rlhf.qmd
          - docs/nccl.qmd
          - docs/mac.qmd
          - docs/multi-node.qmd
          - docs/unsloth.qmd
          - docs/amd_hpc.qmd
      - section: "Dataset Formats"
        contents: docs/dataset-formats/*
      - section: "Reference"
        contents:
          - docs/config.qmd
      - section: "API Reference"
        contents: "{{ api_contents }}"
      - text: "FAQ"
        href: docs/faq.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

quartodoc:
  package: axolotl
  parser: google
  dir: api
  sections:
    - title: Core API
      desc: Core functionality of Axolotl

metadata-files:
  - api/_sidebar.yml
